<a href="https://colab.research.google.com/github/jks5177/BigAI/blob/main/9_%ED%85%8D%EC%8A%A4%ED%8A%B8_%EB%8B%A4%EC%A4%91_%EB%B6%84%EB%A5%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive


In [ ]:
!cp -r /content/gdrive/MyDrive/BigLeaderAI/자연어처리/pytest/네이버뉴스-생활문화_다중 /content/naverNews

# 형태소 분석기 관련 설치

In [ ]:
# java jdk 설치
!apt-get update
!apt-get install g++ openjdk-8-jdk

Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease [3,626 B]
Ign:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Ign:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release [697 B]
Hit:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Get:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release.gpg [836 B]
Hit:8 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:9 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease [15.9 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:11 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Get:12 http://security.ubuntu.com/ubuntu bionic-securi

In [ ]:
#JPype 설치
!pip install JPype1

# RHINO 설치
!pip install rhinoMorph

     |████████████████████████████████| 448 kB 5.1 MB/s 
     |████████████████████████████████| 3.0 MB 6.8 MB/s 


# Data Loading Preparation

In [ ]:
# 경로를 설정하고, 분류할 종류를 리스트로 만든다.
import os

naver_dir = '/content/naverNews'

train_dir = os.path.join(naver_dir, 'train')
test_dir = os.path.join(naver_dir, 'test')

label_types = ['건강정보', '공연전시', '도로교통', '여행레저', '음식맛집',
               '자동차시승기', '종교', '책', '패션뷰티']

In [ ]:
def make_texts_labels(dir, label_types, encoding='utf8') :
  texts = []
  labels = []

  for label_type in label_types :
    dir_name = os.path.join(dir, label_type)
    for fname in os.listdir(dir_name) :
      if fname[-4:] == '.txt' :
        f = open(os.path.join(dir_name, fname), encoding=encoding)
        texts.append(f.read())
        f.close()
        if label_type == label_types[0] :
          labels.append(0)
        elif label_type == label_types[1] :
          labels.append(1)
        elif label_type == label_types[2] :
          labels.append(2)
        elif label_type == label_types[3] :
          labels.append(3)
        elif label_type == label_types[4] :
          labels.append(4)
        elif label_type == label_types[5] :
          labels.append(5)
        elif label_type == label_types[6] :
          labels.append(6)
        elif label_type == label_types[7] :
          labels.append(7)
        elif label_type == label_types[8] :
          labels.append(8)
  return texts, labels

In [ ]:
texts, labels = make_texts_labels(train_dir, label_types)
print('text0:',texts[0])
print('texts len : ', len(texts))
print('labels 0 :', labels[0])
print('labelsl len :', len(labels))
texts

text0: 라즈베리 로즈 입은 LG `G6` : 네이버 뉴스







LG전자가 밸런타인데이 날인 14일 이동통신 3사를 통해 매혹적인 장밋빛으로 인기를 끌고 있는 '라즈베리 로즈' 색상을 입힌 LG G6를 출시한다. LG전자 모델이 'G6 라즈베리 로즈'를 소개하고 있다.  LG전자 제공                                                                             디지털타임스 홈페이지 바로가기 / SNS 바로가기디지털타임스 영문뉴스 바로가기 / 카드뉴스 바로가기


texts len :  90
labels 0 : 0
labelsl len : 90


["라즈베리 로즈 입은 LG `G6` : 네이버 뉴스\n\n\n\n\n\n\n\nLG전자가 밸런타인데이 날인 14일 이동통신 3사를 통해 매혹적인 장밋빛으로 인기를 끌고 있는 '라즈베리 로즈' 색상을 입힌 LG G6를 출시한다. LG전자 모델이 'G6 라즈베리 로즈'를 소개하고 있다.  LG전자 제공                                                                             디지털타임스 홈페이지 바로가기 / SNS 바로가기디지털타임스 영문뉴스 바로가기 / 카드뉴스 바로가기\n\n",
 '자궁적출수술이 여성에게 미치는 영향 : 네이버 뉴스\n\n\n\n\n\n\n\n최근 미국에서 발표된 대규모 연구결과 자궁적출술을 받은 여성일수록 심혈관질환에 노출될 확률이 높은 것으로 보고됐다.“가족계획을 다 마치셨다면 자궁적출술로 문제를 해결하시죠.”주부 박모 씨(43)가 최근 자궁근종으로 진단받은 뒤 들은 이야기다. 더 이상 아이를 가질 생각도 없지만 막상 자궁을 제거한다니 마음이 싱숭생숭하다. 의사에게 다른 치료법은 없냐고 물었지만 ‘가장 확실한 치료법’이라며 자궁적출수술을 추천했다.한국은 OECD 국가 중 자궁적출술 건수가 가장 많은 나라다. 부인과 암과 관련된 경우 자궁적출술이 꼭 필요하지만, 근종 때문이라면 문제가 다르다. 자궁근종은 암으로 악화될 가능성이 낮은 양성종양이다. 월경과다·생리통 등을 유발할 수 있지만 생명에 직접적인 영향을 주지 않는다.민트병원 자궁근종통합센터 김재욱 원장은 “과거 임신계획이 없는 여성에서 자궁근종·자궁선근증이 나타난 경우 자궁적출술을 권유하곤 했다”며 “근종의 위치나 수에 따라 다르지만 자궁적출술은 자궁을 보존하는 자궁절제술보다 쉽고, 임신·출산의 기능을 마친 자궁은 중요한 기능이 없다고 믿었기 때문”이라고 설명했다.실제로 자궁적출수술 후에는 근종이 자랄 자궁이 없으니 재발하는 경우는 없다. 수술 시 난소는 남겨두기 때문에 여성호르몬 분비도 큰 문제가 없다. 다만 최근엔 의학

# Analyzing Morphology

In [ ]:
# 한글은 tokenizing을 위해서 먼저 형태소분석을 해야 한다.
import rhinoMorph
rn = rhinoMorph.startRhino()
texts_list = []

# 리스트 컴프리헨션으로 실질형태소만을 리스트로 가져온다.
for sentence in texts :
  texts_list.append(rhinoMorph.onlyMorph_list(rn, sentence, pos=['NNG','NNP','NP','VV','VA','XR','IC','MM','MAG','MAJ'], eomi=False))

texts = texts_list
print(texts[0])

filepath:  /usr/local/lib/python3.7/dist-packages
classpath:  /usr/local/lib/python3.7/dist-packages/rhinoMorph/lib/rhino.jar
RHINO started!
['라즈', '버리', '로즈', '입', 'LG', '네이버', '뉴스', 'LG', '전자', '밸런타인데이', '날인', '이동통신', '사', '통하', '매혹적', '장밋빛', '인기', '끌', '라즈', '버리', '로즈', '색상', '입히', 'LG', '출시', 'LG', '전자', '모델', '라즈', '베리', '로즈', '소개', '있', 'LG', '전자', '제공', '디지털', '타임스', '홈페이지', '바로', '가', 'SNS', '바로', '가', '디지털', '타임스', '영문', '뉴스', '바로', '가', '카드', '뉴스', '바로', '가']


In [ ]:
%tensorflow_version 2.x
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
import math

validation_raio = math.floor(len(texts)*0.3) # 30%는 검증데이터로 사용한다. 나머지는 훈련데이터
max_words = 10000 # 데이터셋에서 가장 빈도 높은 10,000개의 단어만 사용한다.
maxlen = 200 # 200개 이후의 단어는 버린다.
class_number = 9 # 분류할 클래스의 수

tokenizer = Tokenizer(num_words=max_words) # 상위빈도 10,000개의 단어만을 추려내는 Tokenizer 객체 생성
tokenizer.fit_on_texts(texts) # 단어 인덱스를 구축한다.
word_index = tokenizer.word_index # 단어 인덱스만 가져온다.

# Tokenizing 결과 확인

In [ ]:
print('전체에서 %s개의 고유한 토큰을 찾았습니다.' %len(word_index))
print('word_index type :', type(word_index))
print('word_index:', word_index)

전체에서 5348개의 고유한 토큰을 찾았습니다.
word_index type : <class 'dict'>
word_index: {'하': 1, '되': 2, '있': 3, '뉴스': 4, '네이버': 5, '및': 6, '이': 7, '그': 8, '위하': 9, '기자': 10, '한국': 11, '시간': 12, '가': 13, '받': 14, '배포': 15, '무단': 16, '전재': 17, '대하': 18, '제공': 19, '주': 20, '금지': 21, '김': 22, '서울': 23, '고객': 24, '통하': 25, '올림픽': 26, '평창': 27, '설': 28, '바로': 29, '제품': 30, '작품': 31, '보': 32, '제보': 33, '없': 34, '발생': 35, '작가': 36, '스포츠서울': 37, '밝히': 38, '다양': 39, '서비스': 40, '자궁': 41, '이상': 42, '가장': 43, '시장': 44, '사람': 45, '계획': 46, '정부': 47, '때': 48, '대표': 49, '책': 50, '말하': 51, '진행': 52, '관련': 53, '오': 54, '사진': 55, '따르': 56, '사업': 57, '한경': 58, '컬러': 59, '경우': 60, '약': 61, '지역': 62, '이번': 63, '위': 64, '크': 65, '공식': 66, '나': 67, '교수': 68, '해외': 69, '속': 70, '지난해': 71, '연휴': 72, '가격': 73, '공연': 74, '등': 75, '함께': 76, '지원': 77, '수': 78, '한': 79, '채널': 80, '김지현': 81, '차량': 82, '도로': 83, '핑크': 84, '문제': 85, '국가': 86, '시': 87, '안전': 88, '사량': 89, '많': 90, '기간': 91, '만들': 92, '녹': 93, '여성': 94, '연구': 95, '결과':

# Data Sequencing

In [ ]:
# train 데이터를 Sequencing 한다.
# 상위 빈도 10,000개의 단어를 word_index의 숫자 리스트로 변환
data = tokenizer.texts_to_sequences(texts)

# maxlen의 수만큼으로 길이를 고정한다.
data = pad_sequences(data, maxlen=maxlen)

print('data:', data)

data: [[   0    0    0 ...    4   29   13]
 [ 455  450 1884 ...    6   15   21]
 [ 523  882 1906 ...   33  531   37]
 ...
 [   0    0    0 ...  164  574  575]
 [1899  600   78 ...   33  531   37]
 [   7  497 5315 ...   33  531   37]]


# One-Hot Encoding

In [ ]:
# 원-핫 인코딩 함수
def to_one_hot(labels, dimension) :
  results = np.zeros((len(labels), dimension))
  for i, label in enumerate(labels) :
    results[i, label] = 1
  return results

# 입력층에는 원-핫-인코딩을 수행하지 않는다.
# data = to_one_hot(data, dimension=max_words)

# 출력층만 원-핫-인코딩을 수행한다.
labels = to_one_hot(labels, dimension=class_number)

# Train 데이터와 Validation 데이터 준비

In [ ]:
print('데이터 텐서의 크기 : ', data.shape)
print('레이블 텐서의 크기 : ', labels.shape)

indices = np.arange(data.shape[0])
np.random.shuffle(indices)
data = data[indices]
labels = labels[indices]

x_train = data[validation_raio :]
y_train = labels[validation_raio :]
x_val = data[:validation_raio]
y_val = labels[:validation_raio]

데이터 텐서의 크기 :  (90, 200)
레이블 텐서의 크기 :  (90, 9)


# 모델 정의하기

In [ ]:
# 단어와 임베딩 값의 딕셔너리 로딩
filepath = '/'
embeddings_index = {}
f = open(os.path.join(filepath + 'word2vec', 'embedding_window10_mincnt5_skipgram.txt'),
         encoding='utf-8')
for line in f :
  values = line.split()
  word = values[0]
  coefs = np.asarray(values[1:], dtype='float32')
  embeddings_index[word] = coefs

f.close()

print('%s개의 단어 벡터를 찾습니다.' %len(embeddings_index))

FileNotFoundError: ignored